apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-crud-v1-1-hpa
  namespace: v1-1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-crud-v1-1
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
