apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-crud-v2-hpa
  namespace: v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-crud-v2
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
